
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
    - redis_data:/data

  e-commerce:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
  
  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./secrets/postgres_user:/run/secrets/postgres_user:ro
      - ./secrets/postgres_password:/run/secrets/postgres_password:ro
      - ./secrets/postgres_db:/run/secrets/postgres_db:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$(cat /run/secrets/postgres_user)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend: 
    driver: bridge
  
volumes:
  postgres_data:
  redis_data:
